version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/usr/src/app/assets
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/endless-survival
      - PORT=3000
      - JWT_SECRET=your-super-secure-jwt-secret-change-this-in-production
      - JWT_EXPIRES_IN=90d

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
